travis:
  secure:
    BINSTAR_TOKEN: W/pDEaeWUxFv1L5/ZWBEBLXPQUXeQvyhbRlDDAosY1ADJU9grLoUxfQZ27qD2OLEh3ccNCXBhVWwnfS1VmVo5oEj420nPBDOSG6t3TVXSM0AWlj+xMJ/3SuaDqPT4P1TLnLUV/1sl+v6daynIOgO3ei4vUJIu1viQeTELO0ilMHss39OVmz9Zz1KZc9vysjIbkkFDe6TRSncdOPFwe+PdN3xTm7DC9ZjzjhPJixIpky+sO//g2y8hcyK+OVmhD1yo6vRW45oa4YVRP42PTlK72LcFXsW8HSNdElSUlHo005sIW3psWf6OWLwwIX+vwPoy8zQImSim5xQCXjslZmp+Ks0rf1deTKIBjLXwJ2Pu5kDled7wjFfTWf06WwTWYDq9oc/eURK97MZDCJVb+sidpl4/hb2KXt2d1qxY8r1iBX/f7itDbCX74g/LI5bvlkvFxyEwUumoyAEiz6uBdXmCeGfAq6uu5EG1hQm1flQngYGVy+llhjJrLpOYbBeSh2UEKcRCwN+FPQLrR9B8OScj2fralslhs0NEP2C6IK36nAz7+N1Tk6scczS2D/aHUd1tH4GIhdFhckY/zManglRREDPLackeXKI51q8HCFm3O2BnkfJ6EkKcyNPIFXgCOFGmFy7ArqjD0kZRMyTmShkqzJ3Y0Yh2GefzHCdrTjSrHA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
