travis:
  secure:
    BINSTAR_TOKEN: qZIyyKrUndI2sts4NLbUNWgakvFq8tN27powRkPZMwrOFJzvb/bYhwUfGZ/XsEg8Knuu/8we7EyQc5dCEADtP/BCX5n5DTBtokgpuL0oJsegdVNlehiaT5R7LT8m/UhEiAGS/4ugoOMvWb6NfeWJYNA5kXtnToY9xNIMQMFDHuAU6iwWq3+pZblBsatOzpwRy7DASRKnlQxEUuz10A5Au2Kez3IEK72nOP5IyIowF+wGirSBRCGLdORtTarRX1QmUYMhwWoYClSJ8kaFgNzD+XWn5DOuTOe8s3dGQYUAWOs1CdIJulLjqaU6Fo9LRxrume1VjGavAPOCGyvOTMxbhNt3sDF9RTY/vd95pmxwAbGdorJscpl6MoNl9HprtPwZbN9TUwrma1NjAPgB4pnMzckAuejDQg2OTMIm8sV3a6v9Iu+IncqNLoKf/6jmdfaXncvvm7HIByJEUvVtuO4nZMndL3Qu2BIR5d2OBT7xkpgGyqBZ4BfYZisk8hiWfN55NfNHti4jNEHIUTVRUEXOzEkEgZeu9BG9+PpKeGpVc/2I1gKycoJDpbOjNf54IgAZoj9Q/+PO4ydZQE4EwhccP5QPJIRspMPXoaepYRW5PqZKVDJrPnJ2pxlJNezad8Jb/SF30ybf4rysjtm2P66WeyQaYPMjKYqWq4yOvsZ0U+w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
